pa_wiki:
    resource: "@PAWikiBundle/Resources/config/routing.yml"
    prefix:   /

pa_core:
    resource: "@PACoreBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"